version: '3'

services:
  mysql-server:
    image: mysql:latest
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'employees'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'Orxan299Orxan'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
